angular.module 'clinic'
  .config ($stateProvider, $urlRouterProvider, $locationProvider) ->
    'ngInject'
    $stateProvider
      .state 'home',
        url: '/'
        templateUrl: '/app/components/home/home.html'
        controller: 'HomeController'
        controllerAs: 'home'
      .state 'login',
        url: '/login'
        controller: 'LoginController'
        controllerAs: 'login'
      .state 'register',
        url: '/register'
        templateUrl: '/app/components/register/register.html'
        controller: 'RegisterController'
        constrollerAs: 'register'
      .state 'password_reset',
        url: '/password_reset'
        templateUrl: '/app/components/password_reset/password_reset.html'
      .state 'logout',
        url: '/logout'
      .state 'contact',
        url: '/contact'
        templateUrl: '/app/components/contact/contact.html'
        controller: 'ContactController'
        controllerAs: 'contact'
      .state 'visits',
        url: '/visits'
        abstract: true
        controller: 'VisitsController'
        controllerAs: 'visits'
        template: '<div ui-view></div>'
      .state 'visits.new',
        url: '/new?speciality&doctor&date'
        templateUrl: 'app/components/visits/newVisit.html'
        controller: 'VisitsController'
        controllerAs: 'visits'
      .state 'specialties',
        url: '/specialties'
        templateUrl: '/app/components/specialties/specialties.html'
        controller: 'SpecialtiesController'
        controllerAs: 'specialties'
      .state 'doctors',
        url: '/doctors'
        templateUrl: '/app/components/doctors/doctors.html'
        controller: 'DoctorsController'
        constrollerAs: 'doctors'
      .state 'doctors.detail',
        url: '/:slug'
        templateUrl: '/app/components/doctors/doctor.html'
      .state 'doctors.details.calendar',
        url: '/calendar'
        template: '/app/components/doctors/calendar.html'
      .state 'patient',
        url: '/patient'
        template: '<div ui-view>ddd</div>'
      .state 'patient.change_password',
        url: '/change_password'
      .state 'patient.edit',
        url: '/edit'
      .state 'patient.visits',
        url: '/visits'
        templateUrl: '/app/components/patient/patient.visits.html'
      .state 'patient.visits.show',
        url: '/:id'
      .state 'patient.visits.delete',
        url: '/:id/delete'
      .state 'patient.visits.edit',
        url: '/:id/edit'
      .state 'doctor',
        url: '/doctor'
        templateUrl: 'app/components/doctor/panel.html'
      .state 'doctor-patients',
        url: '/doctor/patients'
        templateUrl: 'app/components/doctor/patients.html'
        controller: 'DoctorPatientsController'
        controllesAs: 'doctor.patients'
      .state 'doctor-patients-new',
        url: '/doctor/patients/new'
        templateUrl: 'app/components/doctor/patients.new.html'
      .state 'doctor-patients-show',
        url: '/doctor/patients/:patientId/show'
        templateUrl: 'app/components/doctor/patients.show.html'
        controller: 'DoctorPatientsController'
        controllerAs: 'doctor.patients.show'
      .state 'doctor.edit',
        url: '/edit'
      .state 'doctor.calendar',
        url: '/calendar'
      .state 'doctor.calendar.edit',
        url: '/edit'
      .state 'doctor.visits',
        url: '/visits'
      .state 'doctor.visits.show',
        url: '/:id'
      .state 'doctor.visits.edit',
        url: '/:id/edit'
      .state 'doctor.visits.comments.new',
        url: '/:id/comments/new'
      .state 'admin',
        url: '/admin'
        templateUrl: 'app/components/admin/panel.html'
      .state 'admin-doctors',
        url: '/admin/doctors'
        templateUrl: 'app/components/admin/doctors.html'
        controller: 'AdminDoctorsController'
        controllesAs: 'admin.doctors'
      .state 'admin-doctors-new',
        url: '/admin/doctors/new'
        templateUrl: 'app/components/admin/doctors.new.html'
        controller: 'AdminDoctorsController'
        controllesAs: 'admin.doctors'
      .state 'admin-doctors-show',
        url: '/admin/doctors/:doctorId/show'
        templateUrl: 'app/components/admin/doctors.show.html'
        controller: 'AdminDoctorsController'
        controllerAs: 'admin.doctors.details'
      .state 'admin-patients',
        url: '/admin/patients'
        templateUrl: 'app/components/admin/patients.html'
        controller: 'AdminPatientsController'
        controllerAs: 'admin.patients'
      .state 'admin-patients-new',
        url: '/admin/patients/new'
        templateUrl: 'app/components/admin/patients.new.html'
      .state 'admin-patients-show',
        url: '/admin/patients/:patientId/show'
        templateUrl: 'app/components/admin/patients.show.html'
        controller: 'AdminPatientsController'
        controllerAs: 'admin.patients.show'
      .state 'admin-patients-edit',
        url: '/admin/patients/:patientId/edit'
        controller: 'AdminPatientsController'
        controllerAs: 'admin.patients.edit'
        templateUrl: 'app/components/admin/patients.edit.html'
      .state 'admin-patients-visits',
        url: '/admin/patients/:patientId/visits'
        controller: 'AdminPatientsVisitsController'
        controllerAs: 'admin.patients.visits.index'
        templateUrl: 'app/components/admin/patients.visits.html'
      .state 'admin-patients-remove',
        url: '/admin/patients/:patientId/remove'
        controller: 'AdminPatientsController'
        controllerAs: 'admin.patients.remove'
      .state 'admin-receptionists',
        url: '/admin/receptionists'
        templateUrl: 'app/components/admin/receptionists.html'
        controller: 'AdminReceptionistsController'
        controllerAs: 'admin.receptionists'
      .state 'admin-receptionists-new',
        url: '/admin/receptionists/new'
        templateUrl: 'app/components/admin/receptionists.new.html'
        controller: 'AdminReceptionistsController'
        controllesAs: 'admin.receptionists'
      .state 'admin-receptionists-show',
        url: '/admin/receptionists/:receptionistId/show'
        templateUrl: 'app/components/admin/receptionists.show.html'
        controller: 'AdminReceptionistsController'
        controllerAs: 'admin.receptionists.show'
      .state 'admin-specialities',
        url: '/admin/specialities'
        templateUrl: 'app/components/admin/specialities.html'
        controller: 'AdminSpecialitiesController'
        controllerAs: 'admin.specialities'
    $urlRouterProvider.otherwise '/'


###


    - receptionist/settings/change_password
    - receptionist/patients/new
    - receptionist/patients/:id
    - receptionist/patients/:id/edit
    - receptionist/patients/:id/visits/:id/delete
    - receptionist/patients/:id/visits/:id/edit
    - receptionist/patients/:id/card
    - receptionist/doctors/:id/edit
    - receptionist/doctors/:id/calendar
    - receptionist/doctors/:id/calendar/edit
    - receptionist/visits/new

    - admin/settings/change_password - admin
    - admin/doctors/new
    - admin/admins/new
    - admin/receptionists/new
    - admin/patients/new
    - admin/patients/:id/edit
    - admin/doctors/:id/edit
    - admin/doctors/:id/calendar
    - admin/doctors/:id/calendar/edit
    - admin/specialties
    - admin/specialties/new
###
